package zone;

import java.io.DataInputStream;
import java.io.IOException;

/**
 * stars in the dataset generated by the SQL script
 */
public class StarScript extends Star {
	public static final int storeSize = 59;

	@Override
	public void set(DataInputStream in) throws IOException {
		in.readInt();	// zoneNum
		ra = Double.longBitsToDouble(Long.reverseBytes(in.readLong()));
		in.readByte();
		dec = Double.longBitsToDouble(Long.reverseBytes(in.readLong()));
		in.readByte();
		x = Double.longBitsToDouble(Long.reverseBytes(in.readLong()));
		in.readByte();
		y = Double.longBitsToDouble(Long.reverseBytes(in.readLong()));
		in.readByte();
		z = Double.longBitsToDouble(Long.reverseBytes(in.readLong()));
		objID = Long.reverseBytes(in.readLong());
		in.readByte();
		margin = Short.reverseBytes(in.readShort()) == 1;
	}

	@Override
	public int size() {
		return storeSize;
	}

}
